[FileDialog]
history=file:///home/arty/Projects/dmis_final_report/website_images, file:///home/arty/Pictures, file:///home/arty/Projects/dmis_final_report/results_images, file:///home/arty/Projects/dmis_final_report/research_images, file:///home/arty/Projects/dmis_project_management_report/images
lastVisited=file:///home/arty/Projects/dmis_project_management_report/images
qtVersion=5.15.13
shortcuts=file:///, file:///home/arty, file:///home/arty/Documents, file:///home/arty/Downloads, file:///home/arty/Pictures, file:///home/arty/Desktop, file:///boot/efi
sidebarWidth=135
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
