[FileDialog]
history=file:///home/arty/Projects/cs355/test_images_lab2/test_images, file:///home/arty/Projects/cs355/func_templates/func_templates, file:///home/arty/Projects/cs355/lab2/result_images_lab2, file:///home/arty/Projects/cs355/lab2, file:///home/arty/Projects/cs355/lab3
lastVisited=file:///home/arty/Projects/cs355/lab3
qtVersion=5.15.16
shortcuts=file:///, file:///home/arty, file:///home/arty/Documents, file:///home/arty/Downloads, file:///home/arty/Pictures, file:///home/arty/Desktop, file:///boot/efi
sidebarWidth=135
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
